server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    username: root
    password: msa
    url: jdbc:mysql://localhost:3304/users?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


